spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1ul2b9w995f2277o.mysql.rds.aliyuncs.com:3306/yunct?useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=25&prepStmtCacheSqlLimit=256&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: ytmall
    password: Yt@163com


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.demo.mapper: debug